name: ci-cd

on:
  push:
    branches: main

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_PHONE: ${{ secrets.TWILIO_PHONE }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          RESEND_KEY: ${{ secrets.RESEND_KEY }}
          API_URL: ${{ secrets.API_URL }}
          WEBSITE_URL: ${{ secrets.WEBSITE_URL }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /home/ubuntu/recipe_book_backend

            docker stop recipes_container
            docker rm recipes_container
            docker rmi recipes_image
            docker system prune -a -f

            git pull

            docker build \
            --build-arg DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            --build-arg JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            --build-arg TWILIO_AUTH_TOKEN="${{ secrets.TWILIO_AUTH_TOKEN }}" \
            --build-arg TWILIO_PHONE="${{ secrets.TWILIO_PHONE }}" \
            --build-arg TWILIO_SID="${{ secrets.TWILIO_SID }}" \
            --build-arg RESEND_KEY="${{ secrets.RESEND_KEY }}" \
            --build-arg API_URL="${{ secrets.API_URL }}" \
            --build-arg WEBSITE_URL="${{ secrets.WEBSITE_URL }}" \
            -t recipes_image .

            docker run -p 4500:4500 --name recipes_container -d recipes_image

          '
