name: ci-cd

on:
  push:
    branches: main

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_PHONE: ${{ secrets.TWILIO_PHONE }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /home/ubuntu/recipe_book_backend
            ./deploy.sh ${{ secrets.DATABASE_URL }} \
              ${{ secrets.JWT_SECRET }} \
              ${{ secrets.TWILIO_AUTH_TOKEN }} \
              ${{ secrets.TWILIO_PHONE }} \
              ${{secrets.TWILIO_SID }} \
          '
